### ISSUE TITLE
NPE+IOOBE for partial default constructor syntax 

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1184]
This code :
```ceylon
class Foo {
    shared new Foo {                  
    }
}
```
when compiled :
```

source\foo\run.ceylon:2: error: missing parameter list in class declaration: 'Foo' must have a parameter list
    shared new Foo {
              ^
source\foo\run.ceylon:2: error: VisibilityVisitor caused an exception visiting Constructor node: java.lang.NullPointerException at com.redhat.ceylon.compiler.typechecker.analyzer.VisibilityVisitor.checkParameterVisibility(VisibilityVisitor.java:90)
    shared new Foo {
              ^
source\foo\run.ceylon:1: error: AnnotationVisitor caused an exception visiting ClassDefinition node: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 at java.util.ArrayList.rangeCheck(ArrayList.java:635)
class Foo {
     ^
```

**Comment by gavinking** [comment]
Fixed, thanks!
