### ISSUE TITLE
CCE for duplicate declaration method+object

### ISSUE THREAD

**Issue by sgalles** [ceylon/ceylon-spec#1236]
This (erroneous) code :
```ceylon

class Foo(){
    
   shared alias Bar => String;
    
    shared void func(Bar b){}
    
    shared object func{}
   
}
```
In the IDE, with both the JVM and JS compilation deactivated :

`RefinementVisitor caused an exception visiting MethodDefinition node: java.lang.ClassCastException: com.redhat.ceylon.compiler.typechecker.model.Value cannot be cast to com.redhat.ceylon.compiler.typechecker.model.Functional at com.redhat.ceylon.compiler.typechecker.analyzer.RefinementVisitor.inheritDefaultedArguments(RefinementVisitor.java:82)`

**Comment by gavinking** [comment]
@sgalles thanks, fixed

**Comment by sgalles** [comment]
@gavinking Now the CCE is fixed, but this code still manages to blow up the JVM backend.
Now I'm not sure, is this a follow up of of the same problem in this issue, or if I should open an issue in `ceylon-compiler`
```
java.lang.StackOverflowError
        at com.redhat.ceylon.compiler.typechecker.model.Declaration.equals(Declaration.java:293)
        at com.redhat.ceylon.compiler.java.codegen.Decl.eq(Decl.java:69)
        at com.redhat.ceylon.compiler.java.codegen.Decl.equal(Decl.java:78)
        at com.redhat.ceylon.compiler.java.codegen.CodegenUtil.getTopmostRefinedDeclaration(CodegenUtil.java:347)
        at com.redhat.ceylon.compiler.java.codegen.CodegenUtil.getTopmostRefinedDeclaration(CodegenUtil.java:246)
        at com.redhat.ceylon.compiler.java.codegen.CodegenUtil.getTopmostRefinedDeclaration(CodegenUtil.java:348)
        at com.redhat.ceylon.compiler.java.codegen.CodegenUtil.getTopmostRefinedDeclaration(CodegenUtil.java:246)
        at com.redhat.ceylon.compiler.java.codegen.CodegenUtil.getTopmostRefinedDeclaration(CodegenUtil.java:348)
        at com.redhat.ceylon.compiler.java.codegen.CodegenUtil.getTopmostRefinedDeclaration(CodegenUtil.java:246)
        at com.redhat.ceylon.compiler.java.codegen.CodegenUtil.getTopmostRefinedDeclaration(CodegenUtil.java:348)
```

**Comment by sgalles** [comment]
@gavinking Maybe I could just open an issue in `ceylon-compiler` to capture this error ? (cf my last message) ?

**Comment by gavinking** [comment]
@sgalles OK, open a new issue so it doesn't get forgotten.

**Comment by gavinking** [comment]
@sgalles Actually I can't reproduce your `StackOverflowError`. At least not in the IDE. Perhaps it's already been fixed.

**Comment by sgalles** [comment]
@gavinking I've open the issue in `ceylon-compiler` because I can reproduce with a fresh env from master (both with the IDE and the CLI)
https://github.com/ceylon/ceylon-compiler/issues/2074
