### ISSUE TITLE
attribute spread operator doesn't work for string

### ISSUE THREAD

**Issue by ePaul** [ceylon/ceylon-spec#1450]
*(I didn't succeed to test this with current master, it doesn't seem to compile currently, or at least on my computer. The described problem happens with the 1.1.0 distribution, though. Feel free to close if it is already fixed.)*

The spread attribute operator [`.*`](http://ceylon-lang.org/documentation/1.1/reference/operator/spread-attribute/) doesn't seem to work on strings.

This works:

    {Character*} ch = "ceylon is awesome!";
    value it = ch*.integer;

This doesn't work:

    value ch = "ceylon is awesome!";
    value it = ch*.integer;

This doesn't work either:

    value it = "ceylon is awesome!"*.integer;

This works:

    value it = ("ceylon is awesome!" of {Character*})*.integer;

As `String` is a subtype of `{Character*}`, I think all of those should work (and assign `it` the same thing, an iterable of the unicode numbers of the characters, i.e. `{99, 101, 121, 108, 111, 110, 32, 105, 115, 32, 97, 119, 101, 115, 111, 109, 101, 33}`).

The IDE is showing this error:

> Cannot find symbol
  symbol:   method getInteger(ceylon.language.Character)
  location: class ceylon.language.String

Using the command line compiler shows this error:

```
$ ~/programme/ceylon-1.1.0/bin/ceylon compile codegolf.ceylon
source/codegolf/ceylon/awesome61660/awesome.ceylon:5: error: cannot find symbol
    value it = ch*.integer;
               ^
  symbol:   method getInteger(Character)
  location: class String
Note: Created module codegolf.ceylon/1.0.0
ceylon compile: Fatal error: The compiler exited abnormally (4) due to a bug in
the compiler.
Please report it:
 https://github.com/ceylon/ceylon-compiler/issues/new
Please include:

* the stacktrace printed below
* a description of what you were trying to compile.

Thank you!
com.redhat.ceylon.compiler.CompilerBugException: Bug
        at com.redhat.ceylon.compiler.CeylonCompileTool.handleExitCode(CeylonCompileTool.java:472)
        at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:454)
        at com.redhat.ceylon.common.tools.CeylonTool.run(CeylonTool.java:352)
        at com.redhat.ceylon.common.tools.CeylonTool.execute(CeylonTool.java:291)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.redhat.ceylon.launcher.Launcher.runInJava7Checked(Launcher.java:104)
        at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:37)
        at com.redhat.ceylon.launcher.Launcher.run(Launcher.java:30)
        at com.redhat.ceylon.launcher.Launcher.main(Launcher.java:23)
Caused by: java.lang.AssertionError
        at com.sun.tools.javac.util.Assert.error(Assert.java:126)
        at com.sun.tools.javac.util.Assert.check(Assert.java:45)
        at com.sun.tools.javac.comp.TransTypes.visitApply(TransTypes.java:601)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1323)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
        at com.sun.tools.javac.comp.TransTypes.translateArgs(TransTypes.java:194)
        at com.sun.tools.javac.comp.TransTypes.visitApply(TransTypes.java:602)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1323)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
        at com.sun.tools.javac.comp.TransTypes.visitAssign(TransTypes.java:642)
        at com.sun.tools.javac.tree.JCTree$JCAssign.accept(JCTree.java:1468)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
        at com.sun.tools.javac.comp.TransTypes.visitExec(TransTypes.java:568)
        at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1169)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
        at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:160)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.visitIf(TransTypes.java:562)
        at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1142)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
        at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:160)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
        at com.sun.tools.javac.comp.TransTypes.visitMethodDef(TransTypes.java:463)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:671)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
        at com.sun.tools.javac.tree.TreeTranslator.visitClassDef(TreeTranslator.java:134)
        at com.sun.tools.javac.comp.TransTypes.translateClass(TransTypes.java:882)
        at com.sun.tools.javac.comp.TransTypes.visitClassDef(TransTypes.java:450)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:593)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
        at com.sun.tools.javac.comp.TransTypes.visitNewClass(TransTypes.java:616)
        at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1374)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
        at com.sun.tools.javac.comp.TransTypes.visitReturn(TransTypes.java:573)
        at com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1242)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
        at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:160)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
        at com.sun.tools.javac.comp.TransTypes.visitMethodDef(TransTypes.java:463)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:671)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
        at com.sun.tools.javac.tree.TreeTranslator.visitClassDef(TreeTranslator.java:134)
        at com.sun.tools.javac.comp.TransTypes.translateClass(TransTypes.java:882)
        at com.sun.tools.javac.comp.TransTypes.visitClassDef(TransTypes.java:450)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:593)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
        at com.sun.tools.javac.comp.TransTypes.visitNewClass(TransTypes.java:616)
        at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1374)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
        at com.sun.tools.javac.comp.TransTypes.visitSelect(TransTypes.java:726)
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1679)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
        at com.sun.tools.javac.comp.TransTypes.visitApply(TransTypes.java:590)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1323)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.tree.TreeTranslator.visitLetExpr(TreeTranslator.java:394)
        at com.sun.tools.javac.comp.TransTypes.visitLetExpr(TransTypes.java:757)
        at com.sun.tools.javac.tree.JCTree$LetExpr.accept(JCTree.java:2113)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
        at com.sun.tools.javac.comp.TransTypes.visitVarDef(TransTypes.java:486)
        at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:727)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
        at com.sun.tools.javac.tree.TreeTranslator.visitBlock(TreeTranslator.java:160)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:783)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
        at com.sun.tools.javac.comp.TransTypes.visitMethodDef(TransTypes.java:463)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:671)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:70)
        at com.sun.tools.javac.tree.TreeTranslator.visitClassDef(TreeTranslator.java:134)
        at com.sun.tools.javac.comp.TransTypes.translateClass(TransTypes.java:882)
        at com.sun.tools.javac.comp.TransTypes.visitClassDef(TransTypes.java:450)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:593)
        at com.sun.tools.javac.tree.TreeTranslator.translate(TreeTranslator.java:58)
        at com.sun.tools.javac.comp.TransTypes.translate(TransTypes.java:429)
        at com.sun.tools.javac.comp.TransTypes.translateTopLevelClass(TransTypes.java:909)
        at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1376)
        at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.desugar(LanguageCompiler.java:774)
        at com.sun.tools.javac.main.JavaCompiler.desugar(JavaCompiler.java:1272)
        at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:871)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:829)
        at com.redhat.ceylon.compiler.java.tools.LanguageCompiler.compile(LanguageCompiler.java:227)
        at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:650)
        at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:566)
        at com.redhat.ceylon.compiler.java.launcher.Main.compile(Main.java:556)
        at com.redhat.ceylon.compiler.CeylonCompileTool.run(CeylonCompileTool.java:453)
        ... 10 more

```

**Comment by ePaul** [comment]
[Here is the full code](http://codegolf.stackexchange.com/a/61747/2338) where I wanted to use this, in `for (c in "ceylon is awesome!"*.string) {`.

**Comment by quintesse** [comment]
This works fine in the current beta Web IDE: http://trybeta.ceylon-lang.org/?src=value%20ch%20=%20%22ceylon%20is%20awesome!%22;%0avalue%20it%20=%20ch*.integer;%0aprint(it);

So I guess this is fixed.

**Comment by sgalles** [comment]
Yes it is already fixed. Actually it was https://github.com/ceylon/ceylon-compiler/issues/2348

**Comment by quintesse** [comment]
Ok, thanks for looking it up @sgalles , dup of ceylon/ceylon-compiler#2348, closing.

**Comment by ePaul** [comment]
@sgalles Thanks, while I looked in ceylon-ide and ceylon-spec for "spread", I didn't check ceylon-compiler.

**Comment by gavinking** [comment]
@ePaul Note that the typechecker doesn't generate errors that look like that. Typechecker errors always have a very recognizable format (they're one-liners, to begin with). And in the IDE, you can distinguish backend errors like this because they are called "Ceylon Backend Error" in the problems list.

HTH
