### ISSUE TITLE
NPE in parser (if expressions)

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-spec#1453]
```ceylon
[]x=if;
```
> java.lang.NullPointerException
	at com.redhat.ceylon.compiler.typechecker.parser.CeylonParser.ifExpression(CeylonParser.java:18663)
	at com.redhat.ceylon.compiler.typechecker.parser.CeylonParser.functionOrExpression(CeylonParser.java:17708)
	at com.redhat.ceylon.compiler.typechecker.parser.CeylonParser.positionalArgument(CeylonParser.java:17248)
	[…]

In the IDE, normal keys cease to work (though you can still remove the `if` line with Ctrl+D).

**Comment by gavinking** [comment]
Fixed, I believe.
